pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js 10.x'
- script: yarn install
- script: yarn electron-pack-linux
  displayName: 'pack for linux'
  env:
     GH_TOKEN: $(GH_TOKEN)